import Head from 'next/head'

import { Card, Button, Layout } from 'antd'

import s from 'styles/Home.module.css'

const { Footer } = Layout

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card className={s.mainCard}>
          On the right is an antd primary button{' '}
          <Button type="primary">Hello World!</Button>
        </Card>
      </main>

      <footer>
        <Footer className={s.footer}>This is a footer</Footer>
      </footer>
    </div>
  )
}
